title: Wild Heretic
description: Controversial research based on the three topics of Dyson Sphere Earth, lost history and transcendentalism.
theme: just-the-docs

url: https://wildheretic.com

# Changing color scheme
color_scheme: custom

# Aux links for the upper right navigation
aux_links:
  Contact: /contact.html
  
nav_external_links:
  - title: Stolenhistory
    url: https://stolenhistory.net
  - title: Cluesforum
    url: https://cluesforum.info
  - title: Fakeologist
    url: https://fakeologist.com
  
  # Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/vitruvian_man.png"
  
# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: ""
    
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
    
    
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
    
